# Dynamic upstream configuration generated by consul-template
# This file is automatically generated - do not edit manually

{{range services}}{{if .Tags | contains "mcp-server"}}
# Upstream configuration for {{.Name}}
upstream {{.Name}}_backend {
    least_conn;
    
    {{range service .Name "passing"}}
    server {{.Address}}:{{.Port}} max_fails=3 fail_timeout=30s weight=1;
    {{else}}
    # No healthy instances available for {{.Name}}
    server 127.0.0.1:65535 backup;
    {{end}}
    
    # Connection pooling
    keepalive 32;
    keepalive_requests 100;
    keepalive_timeout 60s;
}

{{end}}{{end}}

# Health check backend for monitoring all services
upstream health_check_backend {
    server 127.0.0.1:8080;
}

# Monitoring and metrics
upstream consul_backend {
    server consul:8500;
}

{{if service "prometheus"}}
upstream prometheus_backend {
    {{range service "prometheus"}}
    server {{.Address}}:{{.Port}};
    {{end}}
}
{{end}}

{{if service "grafana"}}  
upstream grafana_backend {
    {{range service "grafana"}}
    server {{.Address}}:{{.Port}};
    {{end}}
}
{{end}}